// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Copyright © 2026 Praharsh Nagpure — IPD Studio. Noncommercial use only;
// commercial use requires a paid license (see COMMERCIAL-LICENSE.md).

import { DATASHEET_SECTIONS, fieldsFor } from '../model/datasheet'
import { fieldValue } from '../model/registry'
import type { PlantNode, ProjectDoc } from '../model/types'
import { expandLetters, formatTag } from '../isa/tag'

const esc = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

/** Print a one-page A4 ISA-20-style datasheet form for one instrument. */
export function printDatasheet(doc: ProjectDoc, node: PlantNode): void {
  const letters = node.tag?.letters ?? 'XX'
  const tagText = node.tag ? formatTag(node.tag, '-') : 'UNTAGGED'
  const sections = fieldsFor(letters)
  const rows = (Object.keys(DATASHEET_SECTIONS) as (keyof typeof DATASHEET_SECTIONS)[])
    .map((section) => {
      const fields = sections[section]
      if (!fields.length) return ''
      return (
        `<tr class="sec"><td colspan="2">${section.toUpperCase()}</td></tr>` +
        fields
          .map(
            (f) =>
              `<tr><td class="lbl">${esc(f.label)}</td><td>${esc(fieldValue(doc.registry, node, f.key))}</td></tr>`,
          )
          .join('')
      )
    })
    .join('')

  const iframe = document.createElement('iframe')
  iframe.style.cssText = 'position:fixed;right:0;bottom:0;width:0;height:0;border:0'
  document.body.appendChild(iframe)
  const idoc = iframe.contentDocument
  if (!idoc) return
  idoc.open()
  idoc.write(
    `<!doctype html><html><head><title>${esc(tagText)} datasheet</title><style>` +
      `@page { size: 210mm 297mm; margin: 14mm; }` +
      `body { font: 11px/1.45 sans-serif; color: #111; }` +
      `h1 { font-size: 18px; margin: 0; } .sub { color: #444; margin-bottom: 4mm; }` +
      `table { width: 100%; border-collapse: collapse; }` +
      `td { border: 1px solid #999; padding: 3px 8px; } .lbl { width: 38%; color: #444; }` +
      `.sec td { background: #eee; font-weight: 700; letter-spacing: .06em; }` +
      `.foot { margin-top: 6mm; color: #666; font-size: 10px; display: flex; justify-content: space-between; }` +
      `</style></head><body>` +
      `<h1>INSTRUMENT DATASHEET — ${esc(tagText)}</h1>` +
      `<div class="sub">${esc(expandLetters(letters))} · ${esc(doc.meta.name)}</div>` +
      `<table>${rows}</table>` +
      `<div class="foot"><span>Generated by IPD Studio</span><span>${new Date().toISOString().slice(0, 10)}</span></div>` +
      `</body></html>`,
  )
  idoc.close()
  const win = iframe.contentWindow
  if (!win) return
  win.onafterprint = () => iframe.remove()
  setTimeout(() => {
    win.focus()
    win.print()
    setTimeout(() => iframe.remove(), 60_000)
  }, 100)
}
