// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Copyright © 2026 Praharsh Nagpure — IPD Studio. Noncommercial use only;
// commercial use requires a paid license (see COMMERCIAL-LICENSE.md).

import { SHEET_SIZES_MM, sheetPx } from '../model/doc'
import type { ProjectDoc, Sheet } from '../model/types'
import { activeSheet } from '../store/store'
import { canvasRef } from '../canvas/paperSetup'
import { useStore } from '../store/store'

/** Serialize the current drawing to a standalone SVG document. */
export function exportSvg(_doc: ProjectDoc, sheet: Sheet): string {
  const paper = canvasRef.paper
  if (!paper) throw new Error('Canvas not mounted')
  const { w, h } = sheetPx(sheet.sheetSize)
  const mm = SHEET_SIZES_MM[sheet.sheetSize]

  const clone = paper.svg.cloneNode(true) as SVGSVGElement
  for (const sel of [
    '.joint-tools',
    '.joint-highlighter-layer',
    '.pid-underlay',
    '.pid-sheet',
    '[joint-selector="portBody"]',
    '[joint-selector="portDot"]',
    '[joint-selector="hit"]',
  ]) {
    clone.querySelectorAll(sel).forEach((el) => el.remove())
  }
  // Neutralize the paper's pan/zoom transform on the layers group.
  clone.querySelectorAll('.joint-layers').forEach((el) => el.removeAttribute('transform'))

  const inner = clone.innerHTML
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" width="${mm.w}mm" height="${mm.h}mm" viewBox="0 0 ${w} ${h}">` +
    `<metadata>Generated by IPD Studio</metadata>` +
    `<rect width="${w}" height="${h}" fill="#fff"/>` +
    inner +
    `</svg>`
  )
}

export function exportSvgFile(): void {
  const state = useStore.getState()
  const sheet = activeSheet(state)
  const svg = exportSvg(state.doc, sheet)
  const blob = new Blob([svg], { type: 'image/svg+xml' })
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = `${state.doc.meta.name || 'diagram'}-${sheet.name.replace(/\s+/g, '')}.svg`
  a.click()
  URL.revokeObjectURL(a.href)
}
