import { SHEET_SIZES_MM, sheetPx } from '../model/doc'
import type { ProjectDoc, ProjectMeta } from '../model/types'
import { canvasRef } from '../canvas/paperSetup'
import { useStore } from '../store/store'

const esc = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

/** Sheet border + bottom-right title block, in sheet-local px. */
export function titleBlockSvg(meta: ProjectMeta): string {
  const { w, h } = sheetPx(meta.sheetSize)
  const m = 24 // border margin px (~6.4mm)
  const bw = 420
  const bh = 96
  const bx = w - m - bw
  const by = h - m - bh
  const line = (x1: number, y1: number, x2: number, y2: number) =>
    `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="#111" stroke-width="1"/>`
  const label = (x: number, y: number, t: string) =>
    `<text x="${x}" y="${y}" font-family="sans-serif" font-size="8" fill="#666">${esc(t)}</text>`
  const value = (x: number, y: number, t: string, size = 13) =>
    `<text x="${x}" y="${y}" font-family="sans-serif" font-size="${size}" fill="#111">${esc(t)}</text>`
  const today = new Date().toISOString().slice(0, 10)
  return (
    `<g class="title-block">` +
    `<rect x="${m}" y="${m}" width="${w - 2 * m}" height="${h - 2 * m}" fill="none" stroke="#111" stroke-width="1.5"/>` +
    `<rect x="${bx}" y="${by}" width="${bw}" height="${bh}" fill="#fff" stroke="#111" stroke-width="1.5"/>` +
    line(bx, by + 40, bx + bw, by + 40) +
    line(bx + 240, by, bx + 240, by + bh) +
    line(bx + 240, by + 40 + 28, bx + bw, by + 40 + 28) +
    line(bx + 330, by + 40, bx + 330, by + bh) +
    label(bx + 8, by + 14, 'DRAWING TITLE') +
    value(bx + 8, by + 32, meta.name || 'Untitled', 15) +
    label(bx + 248, by + 14, 'DRAWING No.') +
    value(bx + 248, by + 32, meta.drawingNumber || '—') +
    label(bx + 8, by + 54, 'AUTHOR') +
    value(bx + 8, by + 72, meta.author || '—') +
    label(bx + 248, by + 54, 'REV') +
    value(bx + 248, by + 66, meta.revision || '0') +
    label(bx + 338, by + 54, 'DATE') +
    value(bx + 338, by + 66, today, 11) +
    label(bx + 248, by + 82, 'SHEET') +
    value(bx + 292, by + 92, meta.sheetSize.replace('_', ' '), 11) +
    `</g>`
  )
}

/** Serialize the current drawing to a standalone SVG document. */
export function exportSvg(doc: ProjectDoc): string {
  const paper = canvasRef.paper
  if (!paper) throw new Error('Canvas not mounted')
  const { w, h } = sheetPx(doc.meta.sheetSize)
  const mm = SHEET_SIZES_MM[doc.meta.sheetSize]

  const clone = paper.svg.cloneNode(true) as SVGSVGElement
  for (const sel of ['.joint-tools', '.joint-highlighter-layer', '[joint-selector="portBody"]']) {
    clone.querySelectorAll(sel).forEach((el) => el.remove())
  }
  // Neutralize the paper's pan/zoom transform on the layers group.
  clone.querySelectorAll('.joint-layers').forEach((el) => el.removeAttribute('transform'))

  const inner = clone.innerHTML
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" width="${mm.w}mm" height="${mm.h}mm" viewBox="0 0 ${w} ${h}">` +
    `<metadata>Generated by PID Studio</metadata>` +
    `<rect width="${w}" height="${h}" fill="#fff"/>` +
    inner +
    titleBlockSvg(doc.meta) +
    `</svg>`
  )
}

export function exportSvgFile(): void {
  const doc = useStore.getState().doc
  const svg = exportSvg(doc)
  const blob = new Blob([svg], { type: 'image/svg+xml' })
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = `${doc.meta.name || 'diagram'}.svg`
  a.click()
  URL.revokeObjectURL(a.href)
}
